// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSingleInstance() {
  return window['go']['main']['App']['CheckSingleInstance']();
}

export function CreateAssistant(arg1) {
  return window['go']['main']['App']['CreateAssistant'](arg1);
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CreateMessage(arg1) {
  return window['go']['main']['App']['CreateMessage'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function DeleteAssistant(arg1) {
  return window['go']['main']['App']['DeleteAssistant'](arg1);
}

export function DeleteConversationsAfter(arg1) {
  return window['go']['main']['App']['DeleteConversationsAfter'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFilesByRelatedID(arg1) {
  return window['go']['main']['App']['DeleteFilesByRelatedID'](arg1);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function DeleteTopic(arg1, arg2) {
  return window['go']['main']['App']['DeleteTopic'](arg1, arg2);
}

export function GenerateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['GenerateConversationTitle'](arg1, arg2);
}

export function GenerateStreamID() {
  return window['go']['main']['App']['GenerateStreamID']();
}

export function GenerateSystemPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSystemPrompt'](arg1, arg2, arg3);
}

export function GenerateTopicTitle(arg1) {
  return window['go']['main']['App']['GenerateTopicTitle'](arg1);
}

export function GetActiveStreams() {
  return window['go']['main']['App']['GetActiveStreams']();
}

export function GetAssistantByID(arg1) {
  return window['go']['main']['App']['GetAssistantByID'](arg1);
}

export function GetAssistants() {
  return window['go']['main']['App']['GetAssistants']();
}

export function GetConversations(arg1) {
  return window['go']['main']['App']['GetConversations'](arg1);
}

export function GetDefaultAssistant() {
  return window['go']['main']['App']['GetDefaultAssistant']();
}

export function GetFileByID(arg1) {
  return window['go']['main']['App']['GetFileByID'](arg1);
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetFilesByRelatedID(arg1) {
  return window['go']['main']['App']['GetFilesByRelatedID'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetTopics(arg1) {
  return window['go']['main']['App']['GetTopics'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InitTray() {
  return window['go']['main']['App']['InitTray']();
}

export function IsStreamActive(arg1) {
  return window['go']['main']['App']['IsStreamActive'](arg1);
}

export function OptimizeUserPrompt(arg1) {
  return window['go']['main']['App']['OptimizeUserPrompt'](arg1);
}

export function ProcessFileContent(arg1) {
  return window['go']['main']['App']['ProcessFileContent'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReleaseMutex() {
  return window['go']['main']['App']['ReleaseMutex']();
}

export function SaveFile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopAllStreams() {
  return window['go']['main']['App']['StopAllStreams']();
}

export function StopStreamChatCompletion(arg1) {
  return window['go']['main']['App']['StopStreamChatCompletion'](arg1);
}

export function StreamChatCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamChatCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function TerminateProcess() {
  return window['go']['main']['App']['TerminateProcess']();
}

export function UpdateAssistant(arg1) {
  return window['go']['main']['App']['UpdateAssistant'](arg1);
}

export function UpdateAssistantsSortOrder(arg1) {
  return window['go']['main']['App']['UpdateAssistantsSortOrder'](arg1);
}

export function UpdateConversationSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationSettings'](arg1, arg2);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function UpdateMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMessage'](arg1, arg2, arg3);
}

export function UpdateTopic(arg1) {
  return window['go']['main']['App']['UpdateTopic'](arg1);
}

export function UpdateTopicTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTopicTitle'](arg1, arg2);
}

export function UpdateTopicsSortOrder(arg1) {
  return window['go']['main']['App']['UpdateTopicsSortOrder'](arg1);
}
