// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {map[string]models} from '../models';

export function CheckSingleInstance():Promise<boolean>;

export function CreateAssistant(arg1:{[key: string]: any}):Promise<any>;

export function CreateConversation(arg1:{[key: string]: any}):Promise<string>;

export function CreateMessage(arg1:{[key: string]: any}):Promise<any>;

export function CreateTopic(arg1:{[key: string]: any}):Promise<any>;

export function DeleteAssistant(arg1:string):Promise<void>;

export function DeleteConversationsAfter(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFilesByRelatedID(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function DeleteTopic(arg1:string,arg2:boolean):Promise<void>;

export function GenerateConversationTitle(arg1:string,arg2:string):Promise<string>;

export function GenerateStreamID():Promise<string>;

export function GenerateSystemPrompt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateTopicTitle(arg1:Array<string>):Promise<string>;

export function GetActiveStreams():Promise<map[string]models.StreamInfo>;

export function GetAssistantByID(arg1:string):Promise<any>;

export function GetAssistants():Promise<Array<any>>;

export function GetConversations(arg1:string):Promise<Array<any>>;

export function GetDefaultAssistant():Promise<any>;

export function GetFileByID(arg1:string):Promise<any>;

export function GetFilePath(arg1:string):Promise<string>;

export function GetFilesByRelatedID(arg1:string):Promise<Array<any>>;

export function GetMessages(arg1:string):Promise<Array<any>>;

export function GetTopics(arg1:string):Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function InitTray():Promise<void>;

export function IsStreamActive(arg1:string):Promise<boolean>;

export function OptimizeUserPrompt(arg1:string):Promise<string>;

export function ProcessFileContent(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReleaseMutex():Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string):Promise<any>;

export function ShowWindow():Promise<void>;

export function StopAllStreams():Promise<void>;

export function StopStreamChatCompletion(arg1:string):Promise<void>;

export function StreamChatCompletion(arg1:string,arg2:string,arg3:string,arg4:Array<{[key: string]: any}>,arg5:string):Promise<void>;

export function TerminateProcess():Promise<void>;

export function UpdateAssistant(arg1:{[key: string]: any}):Promise<void>;

export function UpdateAssistantsSortOrder(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateConversationSettings(arg1:string,arg2:string):Promise<void>;

export function UpdateConversationTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTopic(arg1:{[key: string]: any}):Promise<void>;

export function UpdateTopicTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateTopicsSortOrder(arg1:Array<{[key: string]: any}>):Promise<void>;
